/* Generated By:JavaCC: Do not edit this line. Ast0ParserConstants.java */
package ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Ast0ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 6;
  /** RegularExpression Id. */
  int IntLit = 14;
  /** RegularExpression Id. */
  int BoolLit = 15;
  /** RegularExpression Id. */
  int StrLit = 16;
  /** RegularExpression Id. */
  int Digit = 17;
  /** RegularExpression Id. */
  int Letter = 18;
  /** RegularExpression Id. */
  int Id = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\"Assign\"",
    "\"Binop\"",
    "\"Else\"",
    "\"If\"",
    "\"Print\"",
    "\"Unop\"",
    "\"While\"",
    "<IntLit>",
    "<BoolLit>",
    "<StrLit>",
    "<Digit>",
    "<Letter>",
    "<Id>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"!\"",
  };

}
